# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'facebookAuth' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for facebookAuth

  target 'facebookAuth-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'facebookAuthTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'facebookAuth-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for facebookAuth-tvOS

  target 'facebookAuth-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
